using DmOrder.Application.Common.Interfaces;
using DmOrder.Domain.Catalogue;
using DmOrder.Domain.Common;
using DmOrder.Domain.CustomFields;
using DmOrder.Domain.Media;
using DmOrder.Domain.Orders;
using DmOrder.Domain.Stores;
using DmOrder.Infrastructure.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace DmOrder.Infrastructure.Persistence;

public sealed class AppDbContext(DbContextOptions<AppDbContext> options)
    : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>(options), IAppDbContext
{
    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();

    public DbSet<Store> Stores => Set<Store>();

    public DbSet<StoreTheme> StoreThemes => Set<StoreTheme>();

    public DbSet<Category> Categories => Set<Category>();

    public DbSet<Product> Products => Set<Product>();

    public DbSet<ProductImage> ProductImages => Set<ProductImage>();

    public DbSet<CustomField> CustomFields => Set<CustomField>();

    public DbSet<CustomFieldOption> CustomFieldOptions => Set<CustomFieldOption>();

    public DbSet<Customer> Customers => Set<Customer>();

    public DbSet<Order> Orders => Set<Order>();

    public DbSet<OrderItem> OrderItems => Set<OrderItem>();

    public DbSet<OrderFieldValue> OrderFieldValues => Set<OrderFieldValue>();

    public DbSet<MediaAsset> MediaAssets => Set<MediaAsset>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Every IEntityTypeConfiguration in this assembly is picked up automatically, so adding an
        // entity never means editing this method.
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);

        // Ids are generated by the domain (UUID v7 in Entity), never by EF or the database.
        //
        // Without this, EF treats a Guid key as store-generated, and an entity reached through a
        // *navigation collection* with its key already populated is inferred to be an existing row.
        // EF then issues an UPDATE for something that was never inserted, which fails as a phantom
        // concurrency conflict. Explicit Add() calls are unaffected, so this only bites on child
        // collections — product images today, order items and field values later.
        foreach (var entityType in modelBuilder.Model.GetEntityTypes()
                     .Where(t => typeof(Entity).IsAssignableFrom(t.ClrType)))
        {
            modelBuilder.Entity(entityType.ClrType)
                .Property(nameof(Entity.Id))
                .ValueGeneratedNever();
        }
    }

    // DbContext.SaveChangesAsync(CancellationToken) already satisfies IAppDbContext.
}
